---
- name: Create data directory for mongoc configuration server
  file: path=/var/lib/mongodb/configdb state=directory owner=mongodb group=mongodb

- name: Create the mongoc startup file
  template: src=mongoc.service dest=/etc/systemd/system/mongoc.service mode=0644

- name: Create the mongoc configuration file
  template: src=mongoc.conf.j2 dest=/etc/mongoc.conf

- name: Start the mongoc service
  systemd: name=mongoc state=started daemon_reload=yes enabled=yes

#- wait_for:
#    port: "{{ config_port }}"
#    delay: 3

- name: Create the file to initialize mongo config server
  template: src=mongoc_init.js.j2 dest=/tmp/mongoc_init.js
  when: inventory_hostname == groups['mongos'][0]

- name: Init mongo config server
  shell: /usr/bin/mongo "localhost:{{ config_port }}" /tmp/mongoc_init.js
  when: inventory_hostname == groups['mongos'][0]
