---
- name: Config
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify: restart mongod

- name: Enable Mongod
  service:
    name: mongod
    state: started
    
- name: copy initRS script
  run_once: true
  delegate_to: "{{groups[\"mongod\"][item|int]}}"
  template:
    src: initRS.j2
    dest: /tmp/initRS.js
  with_sequence: start=0 end={{(count*replicas) - 1}} stride={{replicas}}

- name: initiate replica set from first primary
  run_once: true
  delegate_to: "{{groups[\"mongod\"][item|int]}}"
  shell: mongo < /tmp/initRS.js
  with_sequence: start=0 end={{(count*replicas) - 1}} stride={{replicas}}

- name: copy addMembers script
  run_once: true
  delegate_to: "{{groups[\"mongod\"][item|int]}}"
  template: src=addMembers.j2 dest=/tmp/addMembers.js
  with_sequence: start=0 end={{(count*replicas) - 1}} stride={{replicas}}
  when: replicas > 1

- name: add members to the replica set
  run_once: true
  delegate_to: "{{groups[\"mongod\"][item|int]}}"
  shell: mongo < /tmp/addMembers.js
  with_sequence: start=0 end={{(count*replicas) - 1}} stride={{replicas}}
  when: replicas > 1
